pub mod ask;
pub mod chat;
pub mod compare;
pub mod config;
pub mod dist;
pub mod doctor;
pub mod models;
pub mod pricing;
pub mod profile;
pub mod setup;
pub mod token;

pub use ask::run_ask;
pub use chat::run_chat;
pub use compare::{run_compare, run_compare_goal};
pub use config::run_config_path;
pub use dist::{run_dist_install, run_dist_status, run_dist_update};
pub use doctor::run_doctor;
pub use models::run_models_list;
pub use pricing::{run_pricing_status, run_pricing_sync};
pub use profile::{run_profile_add, run_profile_list, run_profile_remove, run_profile_use};
pub use setup::run_setup;
pub use token::{run_token_delete, run_token_set};
pub mod token_demo;
pub use token_demo::run_token_demo;
